### PR TITLE
Cleanup before release (adding changelogs, moving unimplemented packages to separate branches)

### PR DESCRIPTION
**Pull request by jbohren**

### CODE REVIEW

**Comment by meyerj** [comment]
Hi John,

I wish you a happy new year!

I started to pull your updates into the hydro-devel branch and did local prerelease tests during the last hour and added some commits myself. I used the [2.7.0-rc1](https://github.com/orocos/rtt_ros_integration/tree/2.7.0-rc1) tag to track the version to be released.

I do not understand all of your commits:
- You said you created branches for the rtt_dynamic_reconfigure, rtt_rosops and rtt_rostime packages. I can see this branches in your repository, but they are also in the hydro-devel branch and only have the deleted packages. I added `CATKIN_IGNORE` markers for these packages in https://github.com/orocos/rtt_ros_integration/commit/fb784f258da6c900241989198ce514d282091169 and removed them from the metapackage rtt_ros_integration in https://github.com/orocos/rtt_ros_integration/commit/dce6b3e5f68c0e7d1becc57af68557f01ab88bef.
  Which way do you prefer?
- Why did you change the URLs of the orocos_toolchain and rtt_ros_integration repositories to SSH in https://github.com/jhu-lcsr-forks/rtt_ros_integration/commit/2f73aa12a89cdc61d716d4a1c7fc1a3019cd7239? I think they are not accessible for anonymous users and Github users without a properly configured SSH key.
  
  I would propose to use `https://git.gitorious.org/orocos-toolchain/orocos_toolchain.git` for orocos_toolchain and `https://github.com/orocos/rtt_ros_integration.git` for rtt_ros_integration. It is also important to specify the branch explicitly if we are not going to rely on the HEAD branch always pointing to the correct revision.
  
  We should also mention that the preferred way to install the toolchain and rtt_ros_integration are the precompiled binaries from the ROS Ubuntu package repository, as the README might also be read by users who already have installed the packages and just want to use rtt_ros_integration.
- I updated the travis config and removed everything that points to https://github.com/jhu-lcsr-forks in https://github.com/orocos/rtt_ros_integration/commit/79fae36b383116070ecc2eaa5659c251c531e711. RTT and OCL are installed by `rosdep`. This seems to work in the meantime with the latest released toolchain packages: https://travis-ci.org/orocos/rtt_ros_integration/builds/16475453. This obsoletes your commit https://github.com/jhu-lcsr-forks/rtt_ros_integration/commit/8e907ddec3fffe22fd600236512402c6468fe2a4.
- Why is the [rtt_rosparam/CHANGELOG.rst](https://github.com/jhu-lcsr-forks/rtt_ros_integration/blob/60edf5b68dcc211d67a4151bbbbc3508b2161571/rtt_rosparam/CHANGELOG.rst) added in https://github.com/jhu-lcsr-forks/rtt_ros_integration/commit/60edf5b68dcc211d67a4151bbbbc3508b2161571 identical to the one in the metapackage rtt_ros_integration? Do we need a `CHANGELOG.rst` in every single package or can we just point to the metapackage?

Johannes

**Comment by meyerj** [comment]
Do you have an idea why the tests are failing in Travis for orocos/rtt_ros_integration.git?
https://travis-ci.org/orocos/rtt_ros_integration/builds/16476426
For some reason Travis still reports a successful build despite of the failed tests.

There are also continuous integration builds including the tests running on Jenkins, which are finally successful since the latest toolchain release: http://jenkins.ros.org/job/devel-hydro-rtt_ros_integration/

**Comment by jbohren** [comment]
> You said you created branches for the rtt_dynamic_reconfigure, rtt_rosops and rtt_rostime packages. I can see this branches in your repository, but they are also in the hydro-devel branch and only have the deleted packages. I added CATKIN_IGNORE markers for these packages in fb784f2 and removed them from the metapackage rtt_ros_integration in dce6b3e.
> Which way do you prefer?

I think we should move these out to keep things cleaner. We can have open tickets to implement them in the future, but since they're not being actively worked on, I think having them there could confuse people.

> Why did you change the URLs of the orocos_toolchain and rtt_ros_integration repositories to SSH in jhu-lcsr-forks@2f73aa1? I think they are not accessible for anonymous users and Github users without a properly configured SSH key.
> 
> I would propose to use https://git.gitorious.org/orocos-toolchain/orocos_toolchain.git for orocos_toolchain and https://github.com/orocos/rtt_ros_integration.git for rtt_ros_integration. It is also important to specify the branch explicitly if we are not going to rely on the HEAD branch always pointing to the correct revision.

That was to move the urls from the jhu fork and the gitorious source just to make it match with the sources that were being tested on travis. I've updated them in 29cc09e to use https instead of ssh and to use gitorious and the toolchain-2.7 branch.

> We should also mention that the preferred way to install the toolchain and rtt_ros_integration are the precompiled binaries from the ROS Ubuntu package repository, as the README might also be read by users who already have installed the packages and just want to use rtt_ros_integration.

Good call. What are the debian package names?

> I updated the travis config and removed everything that points to https://github.com/jhu-lcsr-forks in 79fae36. RTT and OCL are installed by rosdep. This seems to work in the meantime with the latest released toolchain packages: https://travis-ci.org/orocos/rtt_ros_integration/builds/16475453. This obsoletes your commit jhu-lcsr-forks@8e907dd.

Yeah, I accounted for that in the merge.

> Why is the rtt_rosparam/CHANGELOG.rst added in jhu-lcsr-forks@60edf5b identical to the one in the metapackage rtt_ros_integration? Do we need a CHANGELOG.rst in every single package or can we just point to the metapackage?

We don't need a changelog in each package, but I think it will make things simpler going forward, and make the individual changelogs easier to read. I thought I had finished that one, but I clearly haven't. I'll remove it for now, but I want to add migration info for the packages that have changed things.

**Comment by meyerj** [comment]
> > You said you created branches for the rtt_dynamic_reconfigure, rtt_rosops and rtt_rostime packages. I can see this branches in your repository, but they are also in the hydro-devel branch and only have the deleted packages. I added CATKIN_IGNORE markers for these packages in fb784f2 and removed them from the metapackage rtt_ros_integration in dce6b3e.
> > Which way do you prefer?
> 
> I think we should move these out to keep things cleaner. We can have open tickets to implement them in the future, but since they're not being actively worked on, I think having them there could confuse people.

Okay.

> > Why did you change the URLs of the orocos_toolchain and rtt_ros_integration repositories to SSH in jhu-lcsr-forks@2f73aa1? I think they are not accessible for anonymous users and Github users without a properly configured SSH key.
> > 
> > I would propose to use https://git.gitorious.org/orocos-toolchain/orocos_toolchain.git for orocos_toolchain and https://github.com/orocos/rtt_ros_integration.git for rtt_ros_integration. It is also important to specify the branch explicitly if we are not going to rely on the HEAD branch always pointing to the correct revision.
> 
> That was to move the urls from the jhu fork and the gitorious source just to make it match with the sources that were being tested on travis. I've updated them in 29cc09e to use https instead of ssh and to use gitorious and the toolchain-2.7 branch.

Thanks.

> > We should also mention that the preferred way to install the toolchain and rtt_ros_integration are the precompiled binaries from the ROS Ubuntu package repository, as the README might also be read by users who already have installed the packages and just want to use rtt_ros_integration.
> 
> Good call. What are the debian package names?

The Debian package names are the same as the ROS package names, prefixed with `ros-hydro-` and all `_` replaced by `-`. So to install all packages from rtt_ros_integration and typekits one would have to run

```
sudo apt-get install ros-hydro-rtt-ros-integration ros-hydro-rtt-common-msgs
source /opt/ros/hydro/setup.bash
```

This will automatically install the dependencies rtt, ocl and log4cpp, but not the other toolchain packages as long as `ros-hydro-orocos-toolchain` is not explicitly added to the command line.

> > Why is the rtt_rosparam/CHANGELOG.rst added in jhu-lcsr-forks@60edf5b identical to the one in the metapackage rtt_ros_integration? Do we need a CHANGELOG.rst in every single package or can we just point to the metapackage?
> 
> We don't need a changelog in each package, but I think it will make things simpler going forward, and make the individual changelogs easier to read. I thought I had finished that one, but I clearly haven't. I'll remove it for now, but I want to add migration info for the packages that have changed things.

I definitely would not spend the time to write changelogs for each single package (and typekit package) now, but just add a link to https://github.com/orocos/rtt_ros_integration/tree/hydro-devel/rtt_ros_integration/CHANGELOG.rst as a starter. We can use the per-package changelogs in the future and semi-automatically updated them from commit messages using the [catkin_generate_changelog](http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage#bloom.2BAC8-Tutorials.2BAC8-PrepareUpstream.Update_Changelogs) tool.

**Comment by meyerj** [comment]
Successful prerelease of [2.7.0-rc1](https://github.com/orocos/rtt_ros_integration/tree/2.7.0-rc1):
http://jenkins.ros.org/job/prerelease-hydro-rtt_ros_integration/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/2/

**Comment by jbohren** [comment]
Closing, these changes included in https://github.com/orocos/rtt_ros_integration/pull/11

**Comment by jbohren** [comment]
> Do you have an idea why the tests are failing in Travis for orocos/rtt_ros_integration.git?
> https://travis-ci.org/orocos/rtt_ros_integration/builds/16476426
> For some reason Travis still reports a successful build despite of the failed tests.

The tests weren't failing a month ago, and nothing in rtt_ros changed, so I think it might be something that changed in rtt, itself: https://travis-ci.org/jhu-lcsr-forks/rtt_ros_integration/builds/15534262

It also looks like even then, there are some false errors reported even thought things are properly loaded.

I don't know why catkin_make run_tests is returning 0, though.

**Pull request closed without merging**
