### PR TITLE
rtt_roscomm: cleanup of typekit template code

### PR DESCRIPTION
**Pull request by meyerj**
This actually goes back to a refactoring in 56e6a7b where it has been decided to build only one typekit and transport library per package and not one per single message. The source files
- ros_msg_typekit_plugin.cpp
- ros_msg_transport_plugin.cpp
- ros_msg_transport_mqueue_plugin.cpp.in (since #51)

have not been used anymore since then. Other template files have been renamed for consistency.

The cmake variables for collecting the sources have been renamed according to the `target_SOURCES` pattern.

### CODE REVIEW

**Comment by smits** [comment]
lgtm, do we have a test?

**Comment by meyerj** [comment]
There is a test that builds a typekit for a ROS message package and also runs a deployer and imports rtt_std_msgs. The tests are in a separate package [rtt_roscomm_tests](https://github.com/orocos/rtt_ros_integration/tree/642323f7bdbe34237a16d73e32e448b376a8d542/tests/rtt_roscomm_tests) in the `tests` subfolder of the rtt_ros_integration repo.

**Comment by meyerj** [comment]
The file
- ros_msg_typekit_plugin.cpp

was actually still in use. Restored it in amended commit 64dcd65.

**Comment by meyerj** [comment]
Tests passed. I will merge this into corba-support (#62).

**Pull request merged**
